export const routerPathNames = {
  login: '/login',
  dashboard: '/app/dashboard',
  billing: '/app/billing',
  master: {
    category: '/app/master/category',
    brands: '/app/master/brands',
    product: '/app/master/product',
    configMaterial: '/app/master/config-material',
    productMaster: '/app/master/product-master',
    stock: '/app/master/stock',
    customers: '/app/master/customers',
    cafeTables: '/app/master/cafe-tables',
    units: '/app/master/units',
    barCode: '/app/master/barcode',
  },
  inventory: {
    supplier: '/app/inventory/supplier',
    purchase: '/app/inventory/purchase',
    purchaseReturn: '/app/inventory/purchase-return',
    purchaseReport: '/app/inventory/purchase-report',
    purchaseReturnReport: '/app/inventory/purchase-return-report',
    supplierPaymentReport: '/app/inventory/supplier-payment-report',
  },
  statistics: {
    profitAnalysis: '/app/statistics/profit-analysis',
    dashboard: '/app/statistics/dashboard',
    categorySales: '/app/statistics/category-sales',
    productAnalysis: '/app/statistics/product-analysis',
    balanceSummary: '/app/statistics/balance-summary',
  },
  stockReports: {
    currentStock: '/app/stock-reports/current-stock',
    productTransaction: '/app/stock-reports/product-transaction',
    stockAdjustment: '/app/stock-reports/stock-adjustment',
  },
  accountReports: {
    sales: '/app/account-reports/sales',
    salesByCategory: '/app/account-reports/sales-by-category',
    salesByDepartment: '/app/account-reports/sales-by-department',
    salesByItem: '/app/account-reports/sales-by-item',
    salesByCustomer: '/app/account-reports/sales-by-customer',
    salesByAttender: '/app/account-reports/sales-by-attender',
    dayAccount: '/app/account-reports/day-account',
    dayBook: '/app/account-reports/day-book',
    commission: '/app/account-reports/commission',
    gstSalesSummary: '/app/account-reports/gst-sales-summary',
    gstBillWise: '/app/account-reports/gst-bill-wise',
    gstItemWise: '/app/account-reports/gst-item-wise',
    gstHsn: '/app/account-reports/gst-hsn',
    gstPurchase: '/app/account-reports/gst-purchase',
    gstPurchaseSummary: '/app/account-reports/gst-purchase-summary',
  },
  credit: {
    customerBalance: '/app/credit/customer-balance',
    supplierPayment: '/app/credit/supplier-payment',
  },
  users: {
    create: '/app/users/create',
    permission: '/app/users/permission',
    specialPermission: '/app/users/special-permission',
    attender: '/app/users/attender',
    changePassword: '/app/users/change-password',
    discount: '/app/users/discount',
  },
  admin: {
    companyDetails: '/app/admin/company-details',
    editBill: '/app/admin/edit-bill',
    changePaymentType: '/app/admin/change-payment-type',
    exchange: '/app/admin/exchange',
    billDateChangeReport: '/app/admin/bill-date-change-report',
    cancelBillReport: '/app/admin/cancel-bill-report',
    paymentTypeChangeReport: '/app/admin/payment-type-change-report',
    exchangeReport: '/app/admin/exchange-report',
  },
  expense: {
    type: '/app/expense/type',
    entry: '/app/expense/entry',
    report: '/app/expense/report',
  },
  orderList: '/app/order-list',
};
